### ISSUE TITLE
11/23 논의 필요사항

### ISSUE THREAD

**Issue by jeekim2** [HL-Cledor/algoStudy#11]
- Review 방법 전파
- Review request 사용 - 불필요??
- 마저 풀이되지 않은 내용 commit 처리 방안 결정
  1. branch control (PR에 안 올라오게)
  2. PR draft로 변경
- 막히는 풀이에 대한 상의 방법
  - Slack 써보쉴?
- 이 방법이 스터디라고 할 수 있는가
  - 각자 공부(X) 풀이(O) 취합에 불과
  - 문제 풀면서, 이래저래 느낀점, 배운점이 있을텐데 그걸 공유를 해주는게 스터디가 아닐까...
- Review 순환율 저조한 것 같음.
- Test case 얼마나 만드는게 적절?

**Comment by Bobzzang** [comment]
각자 푸는 것에 더 급한거라고 생각됩니다.

Daily Commit으로 인해 매일 문제를 풀기만 하고,
Review를 하는 시간이 부족해지는 게 아닌가 생각됩니다.

Daily Commit에서 문제를 풀이하는 것 뿐만 아니라,
함수에 대한 원리적인 이해나 Review를 하는 것에 대한 것도 좀 고민해봐야 하지 않을까 생각됩니다.

**Comment by YHsla** [comment]
그냥 생각해본것
1. daily commit은 각자 진행하되 요일별로 인원 할당해서 Pull request 진행 > 해당 요일에 해당 인원의 커밋에 대해서만 리뷰에 초점(각자 6일 commit , 1일 review 느낌?)
2. 마저 풀이되지 않은 내용 - 막히는 부분이 있는 경우라 보고 commit은 하되 reviewer들이 힌트를 주는 방향으로(?)
3. 스터디 방식 - 문제 푸는 과정 중 느낀 생각, 궁금증, 질문 등 이슈 등록 >  의견 공유 또는 Issuer가 시간적 여유(주말 등) 있을 때 찾아보고 update

**Comment by hongmyeong-lee** [comment]
slack의 장점이 채팅 기능? 그게 더 있는건가요? 유료인거 같던데 
우선 저의 생각은 실력?이 좀 더 쌓일 때 까지, commit을 좀 해보고 어느정도 감이 오면 그때 부터 reivew를 많이 하는 게 더효율적이라 생각되어 그렇게 하였는데 방향에 대해서 제시해주시면 생각해보겠습니다.

**Comment by Bobzzang** [comment]
**11/23 논의 내용 **
1. PR (Pull Request) 운영 방안
- 현재는 개별적으로 문제를 풀기 때문에, Dependency가 없음.
- Project 관점에서 Module간의 개발이기 때문에 Dependency가 중요함.
- 따라서, 향후 Project 개발에서는 Dependency를 고려하여 협업을 목적으로 사용하길 희망함.

2. Review 관련 (적극 활용 필요)
- Change Request (Change Suggest) 및 Comment 확인하여 Review를 적극 활용 할 것.
- Approval 시점에 대해서도 검토 필요함.
- 각자 공부하고 업데이트 한 거 외에도 Review를 하면서 찾은 내용을 comment로 작성하는 방안으로 활용
- Review하고 Approval해도 Contribution Matrix가 증가함.
- 먼저 Review 수행 후, 이후 문제를 푸는 것을 진행 (Review 순환율 상승 목적)
- Resolve Conversation은 쓰지 말자!

3. 문제 풀이 방식
- 알고리즘 관련 내용은 백준 문제에 작성된 내용 작성해보기
- 인터넷에서 "How to ....(원하는 함수)..." 찾아서 사용 법 공부하기

**Comment by Bobzzang** [comment]
11/23일 논의 사항은 완료 되었으므로, closed issue로 판단됩니다.
