### ISSUE TITLE
LHM 폴더 삭제 안되어있음

### ISSUE THREAD

**Issue by jeekim2** [HL-Cledor/algoStudy#13]
파일 이동 제대로 반영해서 commit - push - Pull request 생성 바랍니다.

**Comment by hongmyeong-lee** [comment]
commit -push는 했는데 pull request가 안되는데

**Comment by hongmyeong-lee** [comment]
review해야 닫히는듯?

**Comment by jeekim2** [comment]
그럼 클로즈를 하면 안되지 이사람아

**Comment by jeekim2** [comment]
Problems\1712_lhm 삭제 요망

**Comment by jeekim2** [comment]
lhm 폴더 삭제 확인 완료
