### ISSUE TITLE
실패한 문제 merge 관련 논의 (각자 의견 comment, 혹은 12/3 논의)

### ISSUE THREAD

**Issue by jeekim2** [HL-Cledor/algoStudy#15]
1. 실패한 문제, 혹은 푸는 중인 문제를 merge가 되도록 하는 것을 용인 할 것인가? (투표)
	1. 찬/반 합당한 이유 제기
2. 용인하지 않는다면, 제제 방안
	1. 벌금
	2. 해당 날짜 contribution 불인정 (결과적으로 벌금)
3. 검출 방안
	1. github Actions 사용 - test case 개발 강제 (이건 공부 해봐야함)
	2. Review 통해 적발 (Reviewer가 좀 귀찮음. 놓칠 수 있음.)
	3. 자수...?
4. 어쨋든 contribution 때문?
	1. 예시
		1. 풀다보니 12시 지나버렸거나, 덜풀었는데 11:59
		2. 도저히 혼자서 견적 안나와서, Help 치고 싶은 경우
	2. 조치방안
		1. 일단 필요한 시점에서 commit 치고, push (기존 PR 있을 경우, 자동으로 들어가게 될 것.)
		2. PR draft 처리
		3. 혼자서 해결이 안되는 경우, Issue 남기기.
5. 본 내용 협의 후, 내용은 정리하여 wiki에 남길 예정.

**Comment by YHsla** [comment]
1.  찬성 / 단, 실패 원인을 기재(단순 시간 부족인지 막히는 부분이 있는지)해서 review를 통해 힌트나 가이드 공유
2. PR draft를 통해 merge는 방지하는 방향도 동의
 - merge의 관점을 공동의 작업물을 수행하는 프로젝트 성격으로 볼 것인지 아님 스터디 커뮤니티 성격으로 볼 것인지에 따라  다를듯.
 -  난 중도 입장이라 둘다 괜찮을듯.
** PR draft : https://hbase.tistory.com/50

**Comment by Bobzzang** [comment]
1. 찬성 
- 현재 진행상황에 대해 전체 인원들이 알 수 있을 것이기 때문에 필요하다고 생각합니다.
- 프로젝트 수준에서도, 현재 완료가 안되었다고 계속해서 Commit을 보류하는 것보다는 현재 본인의 진행상황을 투명하게 보이기 위해서라도 진행 중 commit은 필요하다고 생각합니다. (Merge 및 Approve를 해주지 않는다면 어차피 완료가 되지 않을 것임)

2. PR draft를 통해 merge 및 진행 중인 코드임을 분명하게 분리하는 것은 찬성합니다.
- 단, 현재 PR로 열려있는 상태에서 계속 commit을 하고 있어, 해당 PR을 Draft로 변경하는 방법이 없어보입니다....
- PR이 계속 열려있는 것을 빠르게 Approve하고, 신규 PR Draft를 여는 방법으로 고려하겠습니다.
  (현재 스터디 관점에서는 하루에 1개의 문제를 풀고 있기 때문에, PR Draft가 다수 생길 가능성에 대해서도 우려는 됩니다.)

**Comment by jeekim2** [comment]
저번 세미나 때 내용 전달 했으니 Close 합니다.
안지켜지고있는건 다시 Issue 치겠음.
