### ISSUE TITLE
pytest 사용자 입력 데이터에 대한 테스트 방법 문의

### ISSUE THREAD

**Issue by YHsla** [HL-Cledor/algoStudy#16]
내가 겪고 있는 문제..
1. 함수 내 input() 함수를 통해 사용자 입력 데이터가 필요한 경우, pytest 어떻게 해야 하나...
2. mock 모듈 이용해서 해보려고 하는데..import mock하면 Import "mock" could not be resolved from source 경고가 뜨며 path 인식이 안되는 듯...
3. 원인 및 해결방법을 검색해봐도 잘 모르겠음..
4. 지환이형 파일 참조해보면 monkeypatching 방식으로 해결했는데.. 문법이 검색해도 잘 안나오고 이해가 잘 안되는듯...

같은 문제를 겪고 있거나 해결 방법 또는 참조하기 좋은 링크가 있다면 공유 요청하고자 이슈 등록.

**Comment by Bobzzang** [comment]
Pytest에 대해서는 나도 지환이형 파일 참조하면서 해결하고 있다보니 잘 모르는 부분이 많네ㅠㅠ
실제로 인터넷으로 좀 찾아보니, Monkey Patch를 사용하지 않더라도 Pytest를 실행하는 방법이나 기본적인 설명 자료가 있어보여 아래 링크 공유 합니다. (한글로 된 Blog가 설명은 잘 없고, google에서 상세한 문법이나 설명들이 자세하게 나오는거 같아요)

(1) Pytest 설명 및 기본 사용법
- https://www.guru99.com/pytest-tutorial.html

(2) Monkey patch 관련 
- https://docs.pytest.org/en/latest/how-to/monkeypatch.html
- https://www.codestudyblog.com/cnb11/1124173136.html

**Comment by jeekim2** [comment]
@YHsla 이슈 Assignee를 지정하든지, close 하든 하세여.

**Comment by jeekim2** [comment]
@YHsla 안보니

**Comment by jeekim2** [comment]
@YHsla 언제보니

**Comment by YHsla** [comment]
Close.
재현이 링크 외에 개별 스터디 필요.
