### ISSUE TITLE
그래서 다음번 미팅은 언제?.!

### ISSUE THREAD

**Issue by Bobzzang** [HL-Cledor/algoStudy#25]
그래서 다음번 미팅은 언제가 좋을까요?

목요일 시험 끝나고, 목요일 오후나 금요일?아님 다음주? 의견 남겨 주시죠!

**Comment by jeekim2** [comment]
근무표 확인하고 결정합시당
12월은 재택도 많고 휴가도 많을거라...

**Comment by jeekim2** [comment]
카톡으로 얘기했듯이, 12/14(화) 예정
세미나는 이홍명 준비

**Comment by YHsla** [comment]
화요일 PT 예약되어 있어서 일과중에 짬내서 하면 좋겠습니다.~
4시에 하면 타이트하게 1시간 내로 끝내거나...ㅠ.ㅠ
혹시 홍명이 세미나 일찍 끝나면 저도 이어서 할게요. 정렬 5개 소개하는 수준으로 가볍게 진행할 예정입니다.
