### ISSUE TITLE
잠시...휴가 다녀오겠습니다...(12/15~12/18)

### ISSUE THREAD

**Issue by Bobzzang** [HL-Cledor/algoStudy#38]
잠시...노트북을 버리고 휴가를 떠나고 오겠습니다...

물론, 빵꾸난 Contribution은 열외 없기 때문에 자진납세하겠습니다.

한주도 모두 화이팅!

**Comment by jeekim2** [comment]
잘갔다와서 이슈 닫으셔

**Comment by BitnuriKim** [comment]
다녀오세용
