### ISSUE TITLE
세미나 - YYH

### ISSUE THREAD

**Issue by jeekim2** [HL-Cledor/algoStudy#42]
화요일 PT 예약되어 있어서 일과중에 짬내서 하면 좋겠습니다.~
4시에 하면 타이트하게 1시간 내로 끝내거나...ㅠ.ㅠ
혹시 홍명이 세미나 일찍 끝나면 저도 이어서 할게요. 정렬 5개 소개하는 수준으로 가볍게 진행할 예정입니다.

__Originally posted by @YHsla in https://github.com/HL-Cledor/algoStudy/issues/25#issuecomment-991903768__

**Comment by jeekim2** [comment]
재현 누리 홍명 각각 월화수 출근 안잡아놨던데 조정 가능한사람 조정요

**Comment by BitnuriKim** [comment]
월->화 재택 변경했어요
월요일 점심쯤 하면 좋겠습니다~

**Comment by jeekim2** [comment]
내년으로 연기

**Comment by jeekim2** [comment]
@YHsla 다음주 중 일정 정해주세요.

**Comment by jeekim2** [comment]
@YHsla 새로 일정 수립요

**Comment by YHsla** [comment]
이번주 금요일 목표로 내일 모두에게 일정 문의할게요~

**Comment by YHsla** [comment]
close with the comment가 뭔가해서 눌러봤는데 이슈가 종료되버리네... 
Reopen and comment로 다시 여는 게 있긴 한데 이건 내일 제가 금요일 가능 일정 문의해서 확정할게요~

**Comment by jeekim2** [comment]
@YHsla 까먹지 않으려면 Reopen 해두는게.

**Comment by YHsla** [comment]
일단 제안대로 일정 확정 전까진 Reopen할게요

**Comment by YHsla** [comment]
금일 완료
