### ISSUE TITLE
[공지] 첫 결산 적용 방안

### ISSUE THREAD

**Issue by jeekim2** [HL-Cledor/algoStudy#49]
- 시작일 기준 : github ID 생성일 기준, 2주 간 적응&유예기간 적용
  - 지환/홍명/영한/재현 
  	- github 관련 세미나 11/8 진행 -> 11/22 부터 적용
  - 누리
  	- 11/15 세팅 안내함. -> 11/29 부터 적용
- 적용 기준
  - 기준일 이후, contribution 없을 시 벌금 (1000원/1day)
  - 정산 편의를 위해, 금번 정산에서는 12/31 까지 확인
  - 1월 첫째주 세미나 시 결산
  - 예외사항
    - PR에 명확한 Change Request 없이 3일 이상 Review Approve 가 되지 않은 경우,
      해당 commit에 의한 contribution이 발생 한 것으로 간주 (각자 개별 확인 필요)
    - 결산일 기준, PR에 Change Request가 있는 경우, 해당 PR에 의한 contribution은 불인정
    - 위 예외사항에 의해 계산하기 까다로우니, 리뷰 좀 열심히 했으면 좋겠음.
- 벌금 관리
  - 카카오 모임 통장 개설 예정
  - 해당 통장에 차곡차곡 모아서, 유용하게 씁시다 (책같은거 사거나..)

**Comment by Bobzzang** [comment]
박재현 : 10000원
김빛누리 : 4000원
이홍명 : 2000원
윤영한 : 1000원
김지환 : 0원

**Comment by jeekim2** [comment]
총무할사람 손??

**Comment by jeekim2** [comment]
@BitnuriKim 수금 완료 됐으면 Close요
